# Generated by Django 5.0.4 on 2024-04-07 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='campus_covers/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='campus_profiles/')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('establishment_date', models.DateField()),
                ('number_of_lectures', models.IntegerField(default=0)),
                ('number_of_departments', models.IntegerField(default=0)),
                ('number_of_campuses', models.IntegerField(default=0)),
                ('number_of_colleges', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LecturerCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='lecturer_avatars/')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('skills1', models.CharField(max_length=255)),
                ('skills2', models.CharField(max_length=255)),
                ('skills3', models.CharField(max_length=255)),
                ('skills4', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('education_background', models.CharField(max_length=255)),
                ('background_description', models.TextField()),
                ('education_background2', models.CharField(blank=True, max_length=255, null=True)),
                ('background_description2', models.TextField(blank=True, null=True)),
                ('education_background3', models.CharField(blank=True, max_length=255, null=True)),
                ('background_description3', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(max_length=255)),
                ('languages2', models.CharField(blank=True, max_length=255, null=True)),
                ('languages3', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_experience', models.CharField(max_length=255)),
                ('professional_experience2', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_experience3', models.CharField(blank=True, max_length=255, null=True)),
                ('key_responsibilities', models.TextField()),
                ('key_responsibilities2', models.TextField(blank=True, null=True)),
                ('key_responsibilities3', models.TextField(blank=True, null=True)),
                ('project1', models.CharField(max_length=255)),
                ('project_description1', models.TextField()),
                ('project2', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description2', models.TextField(blank=True, null=True)),
                ('project3', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('text', 'Text')], max_length=10)),
                ('content', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='news_media/')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='university_covers/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='university_profiles/')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('establishment_date', models.DateField()),
                ('number_of_lectures', models.IntegerField(default=0)),
                ('number_of_departments', models.IntegerField(default=0)),
                ('number_of_campuses', models.IntegerField(default=0)),
                ('number_of_colleges', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='user_covers/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='user_profiles/')),
                ('link', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_group_chat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='college_covers/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='college_profiles/')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('establishment_date', models.DateField()),
                ('number_of_lectures', models.IntegerField(default=0)),
                ('number_of_departments', models.IntegerField(default=0)),
                ('number_of_campuses', models.IntegerField(default=0)),
                ('number_of_colleges', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniApp.campusprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='department_covers/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='department_profiles/')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('establishment_date', models.DateField()),
                ('number_of_lectures', models.IntegerField(default=0)),
                ('number_of_departments', models.IntegerField(default=0)),
                ('number_of_campuses', models.IntegerField(default=0)),
                ('number_of_colleges', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniApp.collegeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MediaItemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='comment_avatars/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='UniApp.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaItemDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes_relation', to='UniApp.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaItemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_relation', to='UniApp.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='UniApp.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='UniApp.news'),
        ),
        migrations.AddField(
            model_name='campusprofile',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniApp.universityprofile'),
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_members', to='UniApp.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chat', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='UniApp.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
    ]
