# Generated by Django 5.0.6 on 2024-05-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/advertisements/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/advertisements/videos/')),
                ('call_to_action', models.CharField(blank=True, max_length=255, null=True)),
                ('target_audience', models.JSONField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('landing_page_url', models.URLField(blank=True, null=True)),
                ('metrics_goals', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
