# Generated by Django 5.0.4 on 2024-04-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
