# Generated by Django 5.0.4 on 2024-04-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='GustUser',
        ),
    ]
