# Generated by Django 5.0.4 on 2024-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentprofile',
            name='location',
            field=models.CharField(max_length=555),
        ),
    ]
