# Generated by Django 5.0.6 on 2024-05-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0002_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=10),
        ),
    ]
