# Generated by Django 5.0.4 on 2024-04-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0002_alter_campuspostcomment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegepostcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='collegepostcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='departmentpostcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='departmentpostcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='universitypostcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='universitypostcomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='CampusPostComment',
        ),
        migrations.DeleteModel(
            name='CollegePostComment',
        ),
        migrations.DeleteModel(
            name='DepartmentPostComment',
        ),
        migrations.DeleteModel(
            name='UniversityPostComment',
        ),
    ]
