# Generated by Django 5.0.4 on 2024-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='tokens',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
