# Generated by Django 5.0.4 on 2024-04-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0003_token_tokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='token',
        ),
    ]
