# Generated by Django 5.0.4 on 2024-04-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0004_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='stortoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwttokens', models.CharField(max_length=500)),
            ],
        ),
    ]
