# Generated by Django 5.0.6 on 2024-05-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0004_notification_delete_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
