# Generated by Django 5.0.6 on 2024-05-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
