# Generated by Django 5.0.4 on 2024-04-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0006_jwttoken_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniApp.campusprofile')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniApp.universityprofile')),
            ],
        ),
    ]
