# Generated by Django 5.0.4 on 2024-05-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0008_campusprofile_user_collegeprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
