# Generated by Django 5.0.6 on 2024-05-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0009_rename_object_id_comment_post_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='object_id',
        ),
        migrations.AddField(
            model_name='campuspost',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniApp.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collegepost',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniApp.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentpost',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniApp.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturerpost',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniApp.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitypost',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniApp.comment'),
            preserve_default=False,
        ),
    ]
