# Generated by Django 5.0.4 on 2024-05-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0010_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='recipient',
        ),
    ]
