# Generated by Django 5.0.6 on 2024-05-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0010_rename_post_id_comment_object_id_campuspost_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campuspost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='collegepost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='departmentpost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='lecturerpost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='universitypost',
            name='comment',
        ),
    ]
