# Generated by Django 5.0.6 on 2024-05-15 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0011_remove_campuspost_comment_remove_collegepost_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campus_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniApp.campusprofile')),
                ('college_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniApp.collegeprofile')),
                ('department_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniApp.departmentprofile')),
                ('university_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniApp.universityprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('campus_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_ratings', to='UniApp.campusprofile')),
                ('college_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_ratings', to='UniApp.collegeprofile')),
                ('department_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_ratings', to='UniApp.departmentprofile')),
                ('lab_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_ratings', to='UniApp.universityprofile')),
                ('lecturer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_ratings', to='UniApp.lecturercv')),
                ('university_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_ratings', to='UniApp.universityprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to=settings.AUTH_USER_MODEL)),
                ('campus_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_comments', to='UniApp.campusprofile')),
                ('college_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_comments', to='UniApp.collegeprofile')),
                ('department_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_comments', to='UniApp.departmentprofile')),
                ('university_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_comments', to='UniApp.universityprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
