# Generated by Django 5.0.4 on 2024-05-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0012_alter_message_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
