# Generated by Django 5.0.6 on 2024-05-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0012_labprofile_rating_ratingcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='campus_profile',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='college_profile',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='department_profile',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='lab_profile',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='lecturer_profile',
        ),
    ]
