# Generated by Django 5.0.4 on 2024-05-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0014_chatsession_chatmessage_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
