# Generated by Django 5.0.6 on 2024-05-16 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0015_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='UniversityRating',
        ),
        migrations.CreateModel(
            name='CampusRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('campus_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_ratings', to='UniApp.campusprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('college_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_ratings', to='UniApp.collegeprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('department_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_ratings', to='UniApp.departmentprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('department_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_ratings', to='UniApp.labprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
