# Generated by Django 5.0.4 on 2024-05-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0016_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
