# Generated by Django 5.0.6 on 2024-05-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0017_rename_department_profile_labrating_labprofile_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
