# Generated by Django 5.0.4 on 2024-05-02 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0017_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentprofile',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniApp.campusprofile'),
            preserve_default=False,
        ),
    ]
