# Generated by Django 5.0.4 on 2024-05-03 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0018_departmentprofile_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturercv',
            name='department',
        ),
        migrations.AddField(
            model_name='lecturercv',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniApp.campusprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturercv',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniApp.collegeprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturercv',
            name='departmen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniApp.departmentprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturercv',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UniApp.universityprofile'),
            preserve_default=False,
        ),
    ]
