# Generated by Django 5.0.4 on 2024-05-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0019_remove_lecturercv_department_lecturercv_campus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturercv',
            old_name='departmen',
            new_name='department',
        ),
    ]
