# Generated by Django 5.0.6 on 2024-05-21 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0024_remove_gustuser_age_remove_gustuser_exam_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('field_choices', models.CharField(max_length=255)),
                ('health_condition', models.CharField(max_length=100)),
                ('exam_result', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AsUser',
        ),
    ]
