# Generated by Django 5.0.6 on 2024-05-22 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0028_campuspost_campus_name_campuspost_college_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityprofile',
            name='category',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='city',
            field=models.CharField(choices=[('city1', 'City 1'), ('city2', 'City 2'), ('city3', 'City 3')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='number_of_laboratories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='number_of_libraries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='pobox',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='region',
            field=models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universityprofile',
            name='specific_place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='health_condition_support',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
