# Generated by Django 5.0.6 on 2024-05-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0029_universityprofile_category_universityprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprofile',
            name='category',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Engineering', 'Engineering'), ('Comprehensive', 'Comprehensive'), ('Research', 'Research'), ('Science and Technology', 'Science and Technology')], max_length=22),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='region',
            field=models.CharField(choices=[('Addis Abeba', 'Addis Abeba'), ('Dire Dawa', 'Dire Dawa'), ('Oromia', 'Oromia'), ('Amhara', 'Amhara'), ('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Somali', 'Somali'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('SNNPR', 'SNNPR'), ('Harari', 'Harari'), ('Gambella', 'Gambella')], max_length=20),
        ),
    ]
