# Generated by Django 5.0.6 on 2024-05-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0030_alter_universityprofile_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprofile',
            name='location',
            field=models.CharField(blank=True, max_length=555),
        ),
    ]
