# Generated by Django 5.0.6 on 2024-05-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0031_alter_universityprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprofile',
            name='category',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Engineering', 'Engineering'), ('Comprehensive', 'Comprehensive'), ('Research', 'Research'), ('Science and Technology', 'Science and Technology')], max_length=50),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='city',
            field=models.CharField(choices=[('city1', 'City 1'), ('city2', 'City 2'), ('city3', 'City 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='location',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='region',
            field=models.CharField(choices=[('Addis Abeba', 'Addis Abeba'), ('Dire Dawa', 'Dire Dawa'), ('Oromia', 'Oromia'), ('Amhara', 'Amhara'), ('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Somali', 'Somali'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('SNNPR', 'SNNPR'), ('Harari', 'Harari'), ('Gambella', 'Gambella')], max_length=50),
        ),
    ]
