# Generated by Django 5.0.6 on 2024-05-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0032_alter_universityprofile_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusprofile',
            name='city',
            field=models.CharField(choices=[('city1', 'City 1'), ('city2', 'City 2'), ('city3', 'City 3')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusprofile',
            name='pobox',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campusprofile',
            name='region',
            field=models.CharField(choices=[('Addis Abeba', 'Addis Abeba'), ('Dire Dawa', 'Dire Dawa'), ('Oromia', 'Oromia'), ('Amhara', 'Amhara'), ('Tigray', 'Tigray'), ('Afar', 'Afar'), ('Somali', 'Somali'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('SNNPR', 'SNNPR'), ('Harari', 'Harari'), ('Gambella', 'Gambella')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campusprofile',
            name='specific_place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
