# Generated by Django 5.0.6 on 2024-05-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0033_campusprofile_city_campusprofile_pobox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturercv',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/lecturer_avatars/'),
        ),
    ]
