# Generated by Django 5.0.6 on 2024-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0034_lecturercv_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lab_files/')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='labprofile',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labprofile',
            name='files',
            field=models.ManyToManyField(related_name='lab_profiles', to='UniApp.labfile'),
        ),
    ]
