# Generated by Django 5.0.6 on 2024-05-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0035_labfile_labprofile_description_labprofile_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprofile',
            name='files',
        ),
        migrations.AddField(
            model_name='labfile',
            name='lab_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='UniApp.labprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
