# Generated by Django 5.0.6 on 2024-05-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniApp', '0037_labprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labfile',
            name='file',
            field=models.FileField(upload_to='static/lab_files/'),
        ),
    ]
